version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on: [mongo]
    environment:
      PORT: 3005
      MONGODB_URI: mongodb://mongo:27017/TaskManagement
      JWT_SECRET: TaskManagement
      JWT_EXPIRES_IN: 7d
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "3005:3005"

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=/api
    restart: unless-stopped
    depends_on: [backend]
    environment:
      - REACT_APP_API_URL=/api 
    ports:
      - "3000:80"

volumes:
  mongo-data:
